/*
 * File: app/view/CpInstanceList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CpInstanceList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.cpinstancelist',

    draggable: true,
    frame: true,
    height: 303,
    width: 456,
    resizable: true,
    closable: false,
    collapsed: false,
    collapsible: false,
    header: true,
    title: 'サーバ一覧',
    forceFit: true,
    store: 'SInstanceInfo',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 63,
                    dataIndex: 'region',
                    text: 'rg.'
                },
                {
                    xtype: 'gridcolumn',
                    width: 63,
                    dataIndex: 'instanceId',
                    text: 'InstanceId'
                },
                {
                    xtype: 'gridcolumn',
                    width: 66,
                    dataIndex: 'instanceState',
                    text: 'State'
                },
                {
                    xtype: 'gridcolumn',
                    width: 72,
                    dataIndex: 'placement',
                    text: 'place'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tag_name',
                    text: 'tg.Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'privateIp',
                    text: 'privateIP'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cpu',
                    text: 'cpu'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tag_st',
                    text: 'tg.ST'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tag_ed',
                    text: 'tg.ED'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tag_type',
                    text: 'tg.Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tag_desc',
                    text: 'tg.Desc'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'vpcId',
                    text: 'vpc'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'autorun',
                    text: 'autorun'
                }
            ],
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            ctlTag: 'StopInstance',
                            text: '停止',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            ctlTag: 'StartInstance',
                            text: '起動',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            ctlTag: 'DisableAutoRun',
                            allowDepress: false,
                            enableToggle: false,
                            pressed: false,
                            text: '自動無効',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick2,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            ctlTag: 'DisableAutoRunTest',
                            allowDepress: false,
                            enableToggle: false,
                            pressed: false,
                            text: 'test',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick21,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'combobox',
                            itemId: 'idacckey',
                            fieldLabel: 'Label',
                            hideLabel: true,
                            displayField: 'name',
                            store: 'SInstanceRg',
                            valueField: 'id'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        this.fnInstanceActionCall(button.ctlTag,null);

    },

    onButtonClick1: function(button, e, options) {
        this.fnInstanceActionCall(button.ctlTag,null);

    },

    onButtonClick2: function(button, e, options) {
        this.fnInstanceActionCall(button.ctlTag,null);

    },

    onButtonClick21: function(button, e, options) {
        this.fnInstanceActionCall(button.ctlTag,null);

    },

    GetSeleteInstance: function() {
        //this.MyGridView.
    },

    fnInstanceActionCall: function(acttype, value) {
        switch (acttype){
            case 'StartInstance':
            this.fireEvent('evStartInstance',value);
            break;
            case 'StopInstance':
            this.fireEvent('evStopInstance',value);
            break;
            case 'ViewInstance':
            this.fireEvent('evInstanceListRefresh',value);

            case 'DisableAutoRun':
            this.fireEvent('evDisableAutoRun',value);
            case 'DisableAutoRunTest':
            this.fireEvent('evDisableAutoRunTest',value);

            break;
        }
    }

});