/*
 * File: app/view/CpDomainItemPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CpDomainItemPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.cpdomainitempanel',

    requires: [
        'MyApp.view.CpDmainItemList',
        'MyApp.view.CpItemDetail'
    ],

    hidden: false,
    itemId: 'cpdmainitemlist2',
    layout: {
        type: 'border'
    },
    title: 'ログ一覧',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'cpdmainitemlist',
                    height: 10,
                    itemId: 'cpdmainitemlist1',
                    region: 'center'
                }
            ],
            dockedItems: [
                {
                    xtype: 'cpitemdetail',
                    height: 379,
                    itemId: 'cpitemdetail1',
                    width: 300,
                    collapsed: false,
                    collapsible: true,
                    flex: 0,
                    region: 'south',
                    dock: 'bottom'
                }
            ]
        });

        me.callParent(arguments);
    }

});