/*
 * File: app/view/CpInstanceAct.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CpInstanceAct', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.cpinstanceAct',

    ctlRegion: '',
    width: 150,
    layout: {
        type: 'fit'
    },
    title: 'サーバ分類',

    initComponent: function() {
        var me = this;

        me.addEvents(
            'evTabViewChange',
            'evSearchData',
            'evEditDomain'
        );

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    fnInstanceActionCall: function(type, cond) {

                        if(type.indexOf('Create')>=0||type.indexOf('Delete')>=0)
                        {
                            this.fireEvent('evEditDomain',type,cond);
                            this.ctlRegion = cond.region;
                        }
                        else
                        {
                            //cond = {region:cond.region,domain:cond.domain};

                            this.fireEvent('evSearchData',type,cond);

                        }
                    },
                    ctlRegion: '',
                    height: 255,
                    itemId: 'acttab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 229,
                            itemId: 'iditem',
                            width: 567,
                            layout: {
                                type: 'fit'
                            },
                            title: 'データ',
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'idsrchcond',
                                    title: '検索条件',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'idprefix',
                                            width: 240,
                                            fieldLabel: 'prefix',
                                            displayField: 'vinfo',
                                            store: 'SPrefixInfo',
                                            valueField: 'val'
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'idcommodityid',
                                            width: 240,
                                            fieldLabel: '商材ID',
                                            displayField: 'vinfo',
                                            store: 'SCommodityInfo',
                                            valueField: 'val'
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'idlogtype',
                                            width: 240,
                                            readOnly: false,
                                            fieldLabel: 'logtype',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'vinfo',
                                            store: 'SLogtypeInfo',
                                            valueField: 'val'
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'idappkeyid',
                                            width: 240,
                                            fieldLabel: 'appkeyid',
                                            displayField: 'vinfo',
                                            store: 'SAppkeyInfo',
                                            valueField: 'val'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            itemId: 'idconfirm',
                                            fieldLabel: '未確認のみ',
                                            boxLabel: '',
                                            checked: true
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'button',
                                    ctlTag: 'ViewItems',
                                    dock: 'top',
                                    text: '検索',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick6,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick6: function(button, e, options) {
        var cond = null;
        //検索条件の指定

        var sp = button.ownerCt.down('#idsrchcond');
        var prefix = sp.down('#idprefix');

        var commodityid = sp.down('#idcommodityid');
        var logtype = sp.down('#idlogtype');
        var appkeyid = sp.down('#idappkeyid');
        var confirm = sp.down('#idconfirm');


        cond = {region:null,
            "domain": null,
            prefix:prefix.value,
            commodityid:commodityid.value,
            logtype:logtype.value,
            appkeyid:appkeyid.value,
            confirm:confirm.checked
        };

        button.ownerCt.ownerCt.fnInstanceActionCall(button.ctlTag,cond);

    }

});