/*
 * File: app/view/CpItemDetail.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CpItemDetail', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.cpitemdetail',

    width: 436,
    layout: {
        type: 'fit'
    },
    title: '送信データ詳細',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'textareafield',
                    dock: 'top',
                    height: 108,
                    itemId: 'itemdetailinfo',
                    width: 458,
                    fieldLabel: 'Label',
                    hideLabel: true
                }
            ],
            items: [
                {
                    xtype: 'container',
                    itemId: 'itemct',
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'propertygrid',
                            itemId: 'itemdetailp',
                            autoScroll: true,
                            header: true,
                            title: 'data',
                            source: {
                                
                            }
                        },
                        {
                            xtype: 'propertygrid',
                            itemId: 'itemdetailp2',
                            autoScroll: true,
                            header: true,
                            title: 'request',
                            source: {
                                
                            }
                        },
                        {
                            xtype: 'propertygrid',
                            itemId: 'itemdetailp3',
                            autoScroll: true,
                            header: true,
                            title: 'response',
                            source: {
                                
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});