/*
 * File: app/view/CpDomainList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CpDomainList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.cpdomainlist',

    frame: true,
    height: 303,
    width: 456,
    resizable: true,
    closable: false,
    collapsed: false,
    collapsible: false,
    header: true,
    title: 'サーバ一覧',
    forceFit: true,
    store: 'SDomainInfo',

    initComponent: function() {
        var me = this;

        me.addEvents(
            'evDomainItemDCL'
        );

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 63,
                    dataIndex: 'domain',
                    text: 'domain'
                }
            ],
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    hidden: true,
                    items: [
                        {
                            xtype: 'button',
                            ctlTag: 'StopInstance',
                            text: '作成',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            ctlTag: 'StartInstance',
                            text: '削除',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                itemdblclick: {
                    fn: me.onGridpanelItemDblClick,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        this.fnInstanceActionCall(button.ctlTag,null);

    },

    onButtonClick1: function(button, e, options) {
        this.fnInstanceActionCall(button.ctlTag,null);

    },

    onGridpanelItemDblClick: function(tablepanel, record, item, index, e, options) {
        this.fireEvent('evDomainItemDCL',record,true,tablepanel.ownerCt.itemid);

    }

});