/*
 * File: app/view/CpItemList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CpItemList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.cpitemlist',

    draggable: true,
    frame: true,
    height: 303,
    width: 456,
    resizable: true,
    closable: false,
    collapsed: false,
    collapsible: false,
    header: true,
    title: 'サーバ一覧',
    forceFit: true,
    store: 'SGmoregloggerInfo',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 63,
                    dataIndex: 'prefix',
                    text: 'commodityid'
                },
                {
                    xtype: 'gridcolumn',
                    width: 66,
                    dataIndex: 'logtype',
                    text: 'logtype'
                },
                {
                    xtype: 'gridcolumn',
                    width: 72,
                    dataIndex: 'appkeyid',
                    text: 'appkeyid'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'message',
                    text: 'message'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'data',
                    text: 'data'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cpu',
                    text: 'logtime'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'confirmflg',
                    text: 'confirmflg'
                }
            ],
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            ctlTag: 'ViewItems',
                            text: '検索',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        this.fnInstanceActionCall(button.ctlTag,null);

    },

    fnInstanceActionCall: function(acttype, value) {
        switch (acttype){
            case 'StartInstance':
            this.fireEvent('evStartInstance',value);
            break;
            case 'StopInstance':
            this.fireEvent('evStopInstance',value);
            break;
            case 'ViewInstance':
            this.fireEvent('evInstanceListRefresh',value);

            case 'DisableAutoRun':
            this.fireEvent('evDisableAutoRun',value);
            case 'DisableAutoRunTest':
            this.fireEvent('evDisableAutoRunTest',value);

            break;
        }
    }

});