/*
 * File: app/view/MyPanel6.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel6', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel6',

    height: 336,
    width: 436,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});