/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.CpInstanceAct',
        'MyApp.view.CpDomainList',
        'MyApp.view.CpTestList',
        'MyApp.view.CpDomainItemPanel'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'cpinstanceAct',
                    itemId: 'instanceAct1',
                    width: 250,
                    collapsed: false,
                    collapsible: true,
                    region: 'west'
                },
                {
                    xtype: 'cpdomainlist',
                    height: 448,
                    itemId: 'cpdomainlist1',
                    width: 10,
                    autoScroll: false,
                    region: 'center'
                },
                {
                    xtype: 'cptestlist',
                    hidden: true,
                    itemId: 'cptestlist1',
                    floatable: false,
                    region: 'center',
                    split: false
                },
                {
                    xtype: 'cpdomainitempanel',
                    hidden: true,
                    itemId: 'cpdmainitemlist3',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }

});