/*
 * File: app/model/MdInstanceInfo.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.MdInstanceInfo', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'region'
        },
        {
            name: 'instanceId'
        },
        {
            name: 'instanceState'
        },
        {
            name: 'placement'
        },
        {
            name: 'tag_name'
        },
        {
            name: 'privateIp'
        },
        {
            name: 'tag_type'
        },
        {
            name: 'tag_st'
        },
        {
            name: 'tag_ed'
        },
        {
            name: 'tag_desc'
        },
        {
            name: 'cpu'
        },
        {
            name: 'vpcId'
        },
        {
            name: 'autorun',
            type: 'string'
        }
    ]
});