/*
 * File: app/controller/CInstanceCtl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.CInstanceCtl', {
    extend: 'Ext.app.Controller',

    stores: [
        'SInstanceInfo'
    ],
    views: [
        'CpInstanceAct',
        'CpInstanceList'
    ],

    onPanelEvStartInstance: function(instanceId, eventOptions) {
        var insLst = Ext.ComponentQuery.query('#instanceList1')[0];
        var selRecords = insLst.getSelectionModel().getSelection();

        var ackLst = Ext.ComponentQuery.query('#idacckey')[0];

        var id = selRecords[0].raw.instanceId;
        var rg = selRecords[0].raw.region;

        var ackLst = Ext.ComponentQuery.query('#idacckey')[0];


        this.fnCallAWSAPI(ackLst.value,rg,id,'StartInstance');
    },

    onPanelEvStopInstance: function(instanceId, eventOptions) {
        var insLst = Ext.ComponentQuery.query('#instanceList1')[0];
        var selRecords = insLst.getSelectionModel().getSelection();

        var ackLst = Ext.ComponentQuery.query('#idacckey')[0];

        var id = selRecords[0].raw.instanceId;
        var rg = selRecords[0].raw.region;

        var clbk = function(buttonId){
            if(buttonId != 'ok' )return;

            this.fnCallAWSAPI(ackLst.value,rg,id,'StopInstance');            

        };
        Ext.Msg.show({
            scope:this,
            title: 'ACPJ-AWS',
            msg: 'インスタンスを停止してもよろしいですか？',
            width: 300,
            buttons: Ext.Msg.OKCANCEL,
            fn:clbk,
            icon: Ext.window.MessageBox.INFO
        });



    },

    onPanelEvInstanceListRefresh: function(type, eventOptions) {
        var insLst = Ext.ComponentQuery.query('#instanceList1')[0];
        var ackLst = Ext.ComponentQuery.query('#idacckey')[0];

        var vStore = insLst.store;
        var vProxy = vStore.getProxy();

        //サーバに送信するパラメータを設定
        vProxy.extraParams = {keyid:ackLst.value};

        insLst.store.load();

        insLst.store.clearFilter();

        insLst.store.filter(function(r) {
            var tp = r.get('tag_type');

            if(type=='other')return (tp != 'release' && tp != 'dontstop');


            return (tp == type);
        }
        );



    },

    onPanelEvDisableAutoRun: function(instanceId, eventOptions) {
        var insLst = Ext.ComponentQuery.query('#instanceList1')[0];
        var selRecords = insLst.getSelectionModel().getSelection();

        var id = selRecords[0].raw.instanceId;



        this.fnCallAWSAPI(id,'DisableAutoRun');
    },

    onPanelEvDisableAutoRunTest: function(eventOptions) {
        var insLst = Ext.ComponentQuery.query('#instanceList1')[0];
        var selRecords = insLst.getSelectionModel().getSelection();

        var id = selRecords[0].raw.instanceId;



        this.fnCallTest(id,'DisableAutoRunTest');
    },

    fnCallAWSAPI: function(ackey, rg, id, typ) {

        if(typ===null | id===null){

            Ext.Msg.alert('ACPJ','インスタンスを選択してください。');
            return;

        }


        var data = { CTLTYPE:typ, INSTANCEID:id,keyid:ackey,region:rg }; // POSTリクエストで送信するデータ


        var xmlHttpRequest = new XMLHttpRequest();
        xmlHttpRequest.onreadystatechange = function()
        {
            var READYSTATE_COMPLETED = 4;
            var HTTP_STATUS_OK = 200;

            if( xmlHttpRequest.readyState == READYSTATE_COMPLETED && 
            xmlHttpRequest.status == HTTP_STATUS_OK )
            {
                // レスポンスの表示
                var obj = Ext.JSON.decode(xmlHttpRequest.responseText );
                if(obj.success){


                }
                else
                {
                    Ext.Msg.alert('ACPJ-AWS',obj);
                    return;

                }
            }
        };

        //xmlHttpRequest.open( 'POST', '../modules/instanceCtl.php' );
        xmlHttpRequest.open( 'POST', '../modules/instanceCtlAll.php' );

        // サーバに対して解析方法を指定する
        xmlHttpRequest.setRequestHeader( 'Content-Type', 'application/x-www-form-urlencoded' );

        // データをリクエスト ボディに含めて送信する
        xmlHttpRequest.send( this.EncodeHTMLForm( data ) );



    },

    EncodeHTMLForm: function(data) {

        var params = [];

        for( var name in data )
        {
            var value = data[ name ];
            var param = encodeURIComponent( name ).replace( /%20/g, '+' )
            + '=' + encodeURIComponent( value ).replace( /%20/g, '+' );

            params.push( param );
        }

        return params.join( '&' );

    },

    fnCallTest: function(id, typ) {

        if(typ===null | id===null){

            Ext.Msg.alert('ACPJ','インスタンスを選択してください。');
            return;

        }


        var data = { CTLTYPE:typ, INSTANCEID:id }; // POSTリクエストで送信するデータ


        var xmlHttpRequest = new XMLHttpRequest();
        xmlHttpRequest.onreadystatechange = function()
        {
            var READYSTATE_COMPLETED = 4;
            var HTTP_STATUS_OK = 200;

            if( xmlHttpRequest.readyState == READYSTATE_COMPLETED && 
            xmlHttpRequest.status == HTTP_STATUS_OK )
            {
                // レスポンスの表示
                var obj = Ext.JSON.decode(xmlHttpRequest.responseText );
                if(obj.success){


                }
                else
                {
                    Ext.Msg.alert('ACPJ-AWS',obj);
                    return;

                }
            }
        };

        xmlHttpRequest.open( 'POST', '../modules/instanceAutoRun.php' );

        // サーバに対して解析方法を指定する
        xmlHttpRequest.setRequestHeader( 'Content-Type', 'application/x-www-form-urlencoded' );

        // データをリクエスト ボディに含めて送信する
        xmlHttpRequest.send( this.EncodeHTMLForm( data ) );


    },

    init: function(application) {
        this.control({
            "panel": {
                evStartInstance: this.onPanelEvStartInstance,
                evStopInstance: this.onPanelEvStopInstance,
                evInstanceListRefresh: this.onPanelEvInstanceListRefresh,
                evDisableAutoRun: this.onPanelEvDisableAutoRun,
                evDisableAutoRunTest: this.onPanelEvDisableAutoRunTest
            }
        });
    }

});
